### ISSUE TITLE
App Rejected Due to YouTube TOS violation

### ISSUE THREAD

**Issue by danrabbit** [robertsanseries/karim#21]
Hey thanks for submitting your app to AppCenter. I'm sorry to say that I've had to reject the submission because downloading videos from YouTube constitutes a violation of the YouTube terms of service. We will be amending our developer documentation to clarify that apps should not violate laws or terms of conditions of third-party services they utilize. Thank you very much for your time and effort. We hope that this doesn't deter you from developing other apps for elementary OS.

**Comment by robertsanseries** [comment]
Ok @danrabbit plus I believe that my app as it is not infringe on YouTube TOS, because it's just a front-end for the youtube-dl tool that has public license.

"In jurisdictions that recognize copyright laws, the author or authors
This software dedicates any and all copyright interest in the
Software for the public domain. We make this dedication to the benefit
From the general public and to the detriment of our heirs and
Successors. We want this dedication to be an act of
Waiver of the perpetuity of all present and future rights to this
Software in accordance with copyright law. "- https://github.com/rg3/youtube-dl/blob/master/LICENSE

I can also give examples of several applications that play the same role as videos downoad on different platforms:

Windows:
- ATube Catch
- Vdownload

Mac:
- ClipGrab
- Fastest Free YouTube Downloader
- MacTubes

Linux:
 - ClipGrab
-  Youtube-DLG
 - Youtube-GUI

Android
- iBolt
- TubeMate
- VDownloader

I believe that if my application infringes on TOS, all operating systems (ubuntu / fedora / arch / etc) and linux terminals that allow youtube-dl library usage also do so. :/

For more information, please refer to <http://unlicense.org/>

However, I fully respect the decision of elemental LLC. Of course this will never stop me from creating other applications (which are already under development). : +1:

**Comment by Vistaus** [comment]
@robertsanseries Not to mention the various websites, like KeepVid for example. They have been going for a couple of years now and are the most popular site for downloading YouTube videos, yet Google has not taken any action against them.

**Comment by cassidyjames** [comment]
I wanted to clarify some things here for posterity:

The relevant [YouTube TOS](https://www.youtube.com/static?template=terms) is 5b (emphasis added):

>…You may access Content for your information and personal use solely as intended through the provided functionality of the Service and as permitted under these Terms of Service. **You shall not download any Content unless you see a “download” or similar link displayed by YouTube** on the Service for that Content. You shall not copy, reproduce, distribute, transmit, broadcast, display, sell, license, or otherwise exploit any Content for any other purposes without the prior written consent of YouTube or the respective licensors of the Content…

Repositories having youtube-dl available to install is not the same as installing it and encouraging its use. Further, the license of the code has nothing to do with terms of service for websites that your app (or its dependency) connects to. And lastly just because some website (which may be hosted under a different jurisdiction) does not follow a services TOS does not mean that elementary AppCenter can also allow its violation; it just means someone else is likely going to get a cease-and-desist and/or lawsuit from Google.

Lastly, to clarify: it's not the latent ability to download YouTube videos that is problematic to me, it is the encouraging of breaking the TOS that is. If Karim was designed and advertised to download video from sources that allow it, then it could be a different story.
